### PR TITLE
Display incoming heals with LibClassicHealComm

### PR DESCRIPTION
**Pull request by yannlugrin**
This PR is based on code imported from the master branch of ShadowedUnitFrames, and also
[LunaUnitFrames](https://github.com/Aviana/LunaUnitFrames/blob/master/modules/incheal.lua)

[LibClassicHealComm](https://github.com/Aviana/LibClassicHealComm-1.0) implement incoming heal events behavior for classic that is already used by at least [LunaUnitFrames](https://legacy-wow.com/classic-addons/lunaunitframes/), [HealBot Continued](https://www.curseforge.com/wow/addons/heal-bot-continued), [VuhDo](https://www.curseforge.com/wow/addons/vuhdo).

### CODE REVIEW

**Comment by Nevcairiel** [comment]
LibClassicHealComm and LunaUnitFrames are not sources that any code can be taken, since both of them are in blatant copyright violations.

**Comment by yannlugrin** [comment]
You mean LibClassicHealComm cannot be used in any addons and LunaUnitFrames, HealBot Continued and VuhDo violate blatant copyright by using it?

**Comment by Nevcairiel** [comment]
Luna itself is an unauthorized rip-off of SUF, and LibClassicHealComm is an unauthorized rip-off of LibHealComm-4.0, hence why both were actually banned from Curse.

On ethics alone other raid frames should not be using them. Luckily someone got permission to update LibHealComm-4.0 officially, so that could be used, it just cannot use anything based on Luna or the likes.

**Comment by yannlugrin** [comment]
ok thanks, I was not aware of that because I saw popular addons using it.

I will rewrite the module to not include code from luna (most part coming from SUF master) and also I will wait for an official version of LibHealComm-4.0 to include it and send you a new pull request.

Sorry about that, I really like SUF and will be happy to contribute. Feel free to contact me for any help.

**Comment by Nevcairiel** [comment]
First versions of LibHealComm-4.0 for classic have already been released, so that shouldn't hold you up:
https://www.wowace.com/projects/libhealcomm-4-0

I imagine LibClassicHealComm was still very similar (if not the same), so changing to that should be easy.

**Comment by yannlugrin** [comment]
I have another PR ready that I will submit as soon as possible, but I'm not able to test it for now.

**Pull request closed without merging**
